[project]
name = "adventofcode2025"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "advent-of-code-data",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
    "ruff",
    "mypy",
    "scipy-stubs>=1.15.3.0",
]

[tool.uv]
